# Generated by Django 3.0.8 on 2020-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Picture_url', models.URLField()),
                ('Url_located', models.URLField()),
                ('Category', models.CharField(max_length=80)),
                ('Publication_date', models.CharField(max_length=50)),
                ('Ranting', models.IntegerField()),
                ('Comments', models.TextField(max_length=500)),
                ('Description', models.TextField(max_length=300)),
            ],
        ),
    ]
