# Generated by Django 3.0.8 on 2020-10-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['id'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Picture_url',
            new_name='picture_url',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Publication_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Ranting',
            new_name='ranting',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Url_located',
            new_name='url_located',
        ),
        migrations.AddField(
            model_name='items',
            name='stores',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
