# Generated by Django 3.0.8 on 2020-11-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='items',
            name='picture_url',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='items',
            name='stores',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='url_located',
            field=models.URLField(max_length=400),
        ),
    ]
