# Generated by Django 3.0.8 on 2020-10-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201021_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
